super_ordem_servico_homepage:
    path:     /
    defaults: { _controller: SuperOrdemServicoBundle:Default:create }

super_ordem_servico_oi_fixo:
    path:     /ordem-de-servico/oi-fixo
    defaults: { _controller: SuperOrdemServicoBundle:Default:checkCpf }

super_ordem_servico_oi_tv:
    path:     /ordem-de-servico/oi-tv
    defaults: { _controller: SuperOrdemServicoBundle:Default:checkCpf }

super_ordem_servico_oi_fixo_create:
    path:     /ordem-de-servico/oi-fixo/cadastrar
    defaults: { _controller: SuperOrdemServicoBundle:Default:create, form: true }

super_ordem_servico_oi_tv_create:
    path:     /ordem-de-servico/oi-tv/cadastrar
    defaults: { _controller: SuperOrdemServicoBundle:Default:create, form: false }

super_ordem_servico_oi_fixo_alterar:
    path:     /ordem-de-servico/oi-fixo/alterar
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: true }

super_ordem_servico_oi_tv_alterar:
    path:     /ordem-de-servico/oi-tv/alterar
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: false }

super_ordem_servico_check_cpf:
    path:     /verificar-cpf
    defaults: { _controller: SuperOrdemServicoBundle:Default:checkCpf }

super_ordem_servico_fila_auditor:
    path:     /auditor/fila-de-atendimento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: 1 }

super_ordem_servico_fila_inputador:
    path:     /inputador/fila-de-atendimento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: 2 }

super_ordem_servico_encaminhar:
    path:     /encaminhar/{idOrdemServico}
    defaults: { _controller: SuperOrdemServicoBundle:Default:encaminhar }
