super_ordem_servico_homepage:
    path:     /
    defaults: { _controller: SuperOrdemServicoBundle:Default:create }

super_ordem_servico_oi_fixo:
    path:     /ordem-de-servico/oi-fixo
    defaults: { _controller: SuperOrdemServicoBundle:Default:checkCpf }

super_ordem_servico_oi_tv:
    path:     /ordem-de-servico/oi-tv
    defaults: { _controller: SuperOrdemServicoBundle:Default:checkCpf }

super_ordem_servico_oi_fixo_create:
    path:     /ordem-de-servico/oi-fixo/cadastrar
    defaults: { _controller: SuperOrdemServicoBundle:Default:create, form: true }

super_ordem_servico_oi_tv_create:
    path:     /ordem-de-servico/oi-tv/cadastrar
    defaults: { _controller: SuperOrdemServicoBundle:Default:create, form: false }

super_ordem_servico_oi_fixo_alterar:
    path:     /ordem-de-servico/oi-fixo/alterar
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: true }

super_ordem_servico_oi_tv_alterar:
    path:     /ordem-de-servico/oi-tv/alterar
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: false }

super_ordem_servico_oi_fixo_visualizar:
    path:     /ordem-de-servico/visualizar/oi-fixo
    defaults: { _controller: SuperOrdemServicoBundle:Default:view, form: true }

super_ordem_servico_oi_tv_visualizar:
    path:     /ordem-de-servico/visualizar/oi-tv
    defaults: { _controller: SuperOrdemServicoBundle:Default:view, form: false }

super_ordem_servico_check_cpf:
    path:     /verificar-cpf
    defaults: { _controller: SuperOrdemServicoBundle:Default:checkCpf }

super_ordem_servico_fila_auditor:
    path:     /auditor/fila-de-atendimento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: 1 }

super_ordem_servico_fila_vendedor:
    path:     /vendedor/fila-de-atendimento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: false}

super_ordem_servico_fila_inputador:
    path:     /imputador/fila-de-atendimento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: 2 }

super_ordem_servico_fila_acompanhador:
    path:     /acompanhador/fila-de-atendimento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: 3 }

super_ordem_servico_fila_gerente:
    path:     /gerente/fila-de-atendimento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: null }

super_ordem_servico_comissionamento:
    path:     /gerente/comissionsamento
    defaults: { _controller: SuperOrdemServicoBundle:Default:index, idSituacao: 6 }

super_ordem_servico_encaminhar:
    path:     /encaminhar/{idOrdemServico}
    defaults: { _controller: SuperOrdemServicoBundle:Default:encaminhar }

super_ordem_servico_anexar:
    path:     /anexar
    defaults: { _controller: SuperOrdemServicoBundle:Default:anexar }

super_ordem_servico_download:
    path:     /download/{idOrdemServico}
    defaults: { _controller: SuperOrdemServicoBundle:Default:download }

super_ordem_servico_historico:
    path:     /ordem-de-servico/historico
    defaults: { _controller: SuperOrdemServicoBundle:Default:historico }

super_ordem_servico_historico_view:
    path:     /ordem-de-servico/historico/{idOrdemServico}
    defaults: { _controller: SuperOrdemServicoBundle:Default:historicoView }

super_ordem_servico_oi_fixo_imputar:
    path:     /ordem-de-servico/oi-fixo/imputar-dados
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: true }

super_ordem_servico_oi_tv_imputar:
    path:     /ordem-de-servico/oi-tv/imputar-dados
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: false }

super_ordem_servico_oi_fixo_acompanhar:
    path:     /ordem-de-servico/oi-fixo/acompanhar
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: true }

super_ordem_servico_oi_tv_acompanhar:
    path:     /ordem-de-servico/oi-tv/acompanhar
    defaults: { _controller: SuperOrdemServicoBundle:Default:edit, form: false }

super_ordem_servico_comissionar:
    path:     /gerente/ordem-de-servico/comissionar
    defaults: { _controller: SuperOrdemServicoBundle:Default:comissionar }

super_ordem_servico_configurar_comissao:
    path:     /gerente/comissao/configurar
    defaults: { _controller: SuperOrdemServicoBundle:ConfiguracaoComissao:index }