super_usuario:
    path:     /administrativo/usuario
    defaults: { _controller: SuperUsuarioBundle:Usuario:index }

super_usuario_create:
    path:     /administrativo/usuario/cadastrar
    defaults: { _controller: SuperUsuarioBundle:Usuario:create }

super_usuario_edit:
    path:     /administrativo/usuario/editar
    defaults: { _controller: SuperUsuarioBundle:Usuario:edit }

###### manter perfil
super_perfil:
    path:     /administrativo/perfil
    defaults: { _controller: SuperUsuarioBundle:Perfil:index }

super_perfil_edit:
    path:     /administrativo/perfil/editar
    defaults: { _controller: SuperUsuarioBundle:Perfil:edit }