services:
    service.usuario:
          class: Super\UsuarioBundle\Service\Usuario
          arguments:  ["@service_container"]

    service.usuario_perfil:
          class: Super\UsuarioBundle\Service\UsuarioPerfil
          arguments:  ["@service_container"]

    service.perfil:
          class: Super\UsuarioBundle\Service\Perfil
          arguments:  ["@service_container"]

    service.pessoa:
          class: Super\UsuarioBundle\Service\Pessoa
          arguments:  ["@service_container"]

    service.pessoa_fisica:
          class: Super\UsuarioBundle\Service\PessoaFisica
          arguments:  ["@service_container"]