services:
    service.email_error:
        class: Base\BaseBundle\Service\EmailError
        arguments:  ["@service_container"]

    service.endereco:
        class: Base\BaseBundle\Service\Endereco
        arguments:  ["@service_container"]

    service.estado:
        class: Base\BaseBundle\Service\Estado
        arguments:  ["@service_container"]

    service.municipio:
        class: Base\BaseBundle\Service\Municipio
        arguments:  ["@service_container"]

    service.bairro:
        class: Base\BaseBundle\Service\Bairro
        arguments:  ["@service_container"]

    app.twig_combo_situacao_extension:
        class: Base\BaseBundle\Twig\ComboSituacaoExtension
        arguments:  ["@service_container"]
        tags:
            - { name: twig.extension }
