super_home:
    path:     /super
    defaults: { _controller: SuperBaseBundle:Default:index }

super_usuario:
    resource: "@SuperUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

super_ordem_servico:
    resource: "@SuperOrdemServicoBundle/Resources/config/routing.yml"
    prefix:   /

super_security:
    resource: "@SuperSecurityBundle/Resources/config/routing.yml"