super_solicitacao_homepage:
    path:     /
    defaults: { _controller: SuperSolicitacaoBundle:Default:create }

super_solicitacao_oi_fixo:
    path:     /oi-fixo
    defaults: { _controller: SuperSolicitacaoBundle:Default:checkCpf }

super_solicitacao_oi_tv:
    path:     /oi-tv
    defaults: { _controller: SuperSolicitacaoBundle:Default:checkCpf }

super_solicitacao_oi_fixo_create:
    path:     /oi-fixo/cadastrar
    defaults: { _controller: SuperSolicitacaoBundle:Default:create }

super_solicitacao_oi_tv_create:
    path:     /oi-tv/cadastrar
    defaults: { _controller: SuperSolicitacaoBundle:Default:create }

super_solicitacao_check_cpf:
    path:     /verificar-cpf
    defaults: { _controller: SuperSolicitacaoBundle:Default:checkCpf }
