services:
    service.solicitacao:
          class: Super\SolicitacaoBundle\Service\Solicitacao
          arguments:  ["@service_container"]

    service.plano:
          class: Super\SolicitacaoBundle\Service\Plano
          arguments:  ["@service_container"]

    service.solicitacao_plano:
          class: Super\SolicitacaoBundle\Service\SolicitacaoPlano
          arguments:  ["@service_container"]


