services:
    service.solicitacao:
          class: Super\SolicitacaoBundle\Service\Solicitacao
          arguments:  ["@service_container"]

    service.plano:
          class: Super\SolicitacaoBundle\Service\Plano
          arguments:  ["@service_container"]

    service.solicitacao_plano:
          class: Super\SolicitacaoBundle\Service\SolicitacaoPlano
          arguments:  ["@service_container"]

    service.velocidade:
          class: Super\SolicitacaoBundle\Service\Velocidade
          arguments:  ["@service_container"]

    service.ordem_servico:
          class: Super\SolicitacaoBundle\Service\OrdemServico
          arguments:  ["@service_container"]

    service.situacao:
          class: Super\SolicitacaoBundle\Service\Situacao
          arguments:  ["@service_container"]

    service.historico:
          class: Super\SolicitacaoBundle\Service\Historico
          arguments:  ["@service_container"]


